In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from cycler import cycler
import pickle

In [22]:
f_name = "/Users/mislam1/Documents/RA/research-2018/ad_rakib/ad_examples/python/baseline_result"
with open(f_name, 'rb') as f:
    loaded_object = pickle.load(f)

In [35]:
def plot_results(ds_result):
    """Plot the results"""
    plots_needed = ["f1"] # ["f1", "auc", "precision", "recall"]
    result_name = ["rf_result", "default_result"]
    default_cycler = (cycler(color=['r', 'g', 'b', 'k']) *
                      cycler(linestyle=['-', '--']))
    ds_available = ds_result.keys()
    for c_plot in plots_needed:
        for ds in ds_available:
            for rs_name in result_name:
                if c_plot is "f1":
                    r_list = ds_result[ds][rs_name].f1_list
                elif c_plot is "auc":
                    r_list = ds_result[ds][rs_name].auc_list
                elif c_plot is "precision":
                    r_list = ds_result[ds][rs_name].precision_list
                elif c_plot is "recall":
                    r_list = ds_result[ds][rs_name].recall_list
                print(r_list)
                if len(r_list) == 1:
                    r_list = r_list * 5
                if "default" in rs_name:
                    c_label = ds + "-w/o time aware"
                    c_marker = '*'
                    c_style = "--"
                else:
                    c_label = ds
                    c_marker = 'o'
                    c_style = "-"


                plt.plot(range(2012, 2017), r_list, label=c_label,
                         marker=c_marker)
                plt.rc('axes', prop_cycle=default_cycler)

        # plt.xlabel("Testing year", fontsize=18)
        # plt.ylabel("F1 Score", fontsize=20)
        # plt.yticks(fontsize=14)
        # plt.ylim(0, 1)
        # plt.xticks(np.arange(5), ('2012', '2013', '2014', '2015', '2016'), fontsize=14)
        # plt.legend(prop={'size': 16}, loc='upper right')
        plt.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc='lower left',
           ncol=2, mode="expand", borderaxespad=0.)
        plt.savefig(c_plot + "-challenge.pdf", bbox_inches='tight')
        plt.close()

In [36]:
plot_results(loaded_object)

[0.5934031311654515, 0.4274246309747234, 0.5513800539122767, 0.5568829832167357, 0.5111779992813867]
[0.8227593486430416]
[0.8153127170951147, 0.46028113762667544, 0.6457079766430138, 0.6050314321810738, 0.542940023900115]
[0.8979834753210865]
[0.327392621636072, 0.36577893000235684, 0.37976994705130546, 0.31587251498895547, 0.31504591476336236]
[1.0]
[0.732465600897668, 0.5114897067040636, 0.6290300902202584, 0.5693798911532197, 0.5442484569527576]
[0.795036883104257]

In [2]:
ad_loc = "/Users/mislam1/Documents/RA/research-2018/ad_rakib/ad_examples/datasets/anomaly/Adadroid/fullsamples/Adadroid_1.csv"

In [3]:
df = pd.read_csv(ad_loc)

In [4]:
df.shape

(20858, 385)

In [5]:
df.head(2)

,label,feat-0,feat-1,feat-2,feat-3,feat-4,feat-5,feat-6,feat-7,feat-8,...,feat-374,feat-375,feat-376,feat-377,feat-378,feat-379,feat-380,feat-381,feat-382,feat-383
0,anomaly,0.0,0.0,0.0,0.8711,0.1289,0.0,0.0000,0.0,0.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,anomaly,0.0,0.0,0.0,0.1528,0.0056,0.0,0.4152,0.0,0.4264,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
n_df = df.iloc[:, (100 + 122):]

In [12]:
n_df['label'] = df['label']

In [14]:
cols = n_df.columns.tolist()
cols.insert(0, cols.pop(cols.index('label')))

In [17]:
nn_df = n_df.reindex(columns=cols)

In [19]:
nn_df.shape

(20858, 164)

In [20]:
nn_df.to_csv("/Users/mislam1/Documents/RA/research-2018/ad_rakib/ad_examples/datasets/anomaly/Afonso/fullsamples/" + "Afonso_1.csv", index=False)